### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by aayush1607**
Linked style.css and made changes in alternative text as suggested.

### CODE REVIEW

**Comment by thisisabdus** [comment]
Probably forgot to add your `style.css` file :sweat_smile:

**Comment by aayush1607** [comment]
Sorry .I made another pull request for that.

**Comment by aayush1607** [comment]
I am new to git so sometimes i make mistakes. Thank you for helping.

**Comment by thisisabdus** [comment]
Alright. No prob. Merging...

**Pull request merged**
