### PR TITLE
Submit Ashish's Task

### PR DESCRIPTION
**Pull request by pixan198**

### CODE REVIEW

**Comment by thisisabdus** [comment]
Also, please fix conflicts.

**Comment by pixan198** [comment]
Conflicts are because you'd suggested me to make some changes in task2

**Comment by pixan198** [comment]
If I make changes in my forked repo will this pr get updated?

**Comment by thisisabdus** [comment]
Yep, it will.

**Comment by pixan198** [comment]
Okay

**Comment by pixan198** [comment]
I've added user input for the date in task4

**Comment by thisisabdus** [comment]
you can change commit message by doing a git rebase. 
https://linuxize.com/post/change-git-commit-message/

**Comment by pixan198** [comment]
@thisisabdus yes, that article helped but when I ran the command `git rebase -i HEAD~2` there were various merge conflicts in other people's folders so, I'd to abort Rebase.

What should I do next?

**Comment by thisisabdus** [comment]
Rebasing is a way to rewrite commit message. No worries tho, I will squash them before merge and correct those commit messages.

**Comment by pixan198** [comment]
Yeah
Thank you @thisisabdus

**Pull request merged**
