### PR TITLE
master

### PR DESCRIPTION
**Pull request by saksham2001**
saksham2001 task1

### CODE REVIEW

**Comment by MadhavBahlMD** [comment]
Please delete the `thankyou.html` file

**Comment by HarshKapadia2** [comment]
You have forgotten to add a `no` radio button for some options.
Both the options read `yes` haha
It's just a typo, so do correct it!

**Comment by HarshKapadia2** [comment]
Also, please delete `thankyou.html` as @MadhavBahlMD has suggested above.

**Comment by MadhavBahlMD** [comment]
Closing the PR
please don't change code in other folders

**Pull request closed without merging**
